name: test_face_detaction
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_face_detection: ^0.13.1
  camera: ^0.11.0+2
  google_mlkit_commons: ^0.11.0
  flutter_hooks: ^0.21.2
  tflite_flutter: ^0.12.1
  image_picker: ^1.1.2
  image: ^4.7.2
  # tflite_flutter_helper: ^0.2.1
  # tflite_flutter: ^0.9.5

  flu_wake_lock:
    git: https://github.com/sovannDeveloper/wakelock.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/models/mobilefacenet.tflite