name: test_face_detection
description: "Test face detection."
publish_to: 'none' 
version: 1.0.0+26

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  tflite_flutter:
    path: ./tflite_flutter
  flu_wake_lock:
    git: https://github.com/sovannDeveloper/wakelock.git
  division:
    git: https://github.com/sovannDeveloper/division.git
  path_provider: ^2.1.5
  remix: ^0.0.4
  remixicon: ^1.4.1
  camera: ^0.11.3
  image_picker: ^1.2.1
  image: ^4.7.2
  google_mlkit_face_detection: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/images/