name: test_face_detaction
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+9

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_face_detection: ^0.13.1
  tflite_flutter: ^0.12.1
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image: ^4.7.2

  flu_wake_lock:
    git: https://github.com/sovannDeveloper/wakelock.git
  division:
    git: https://github.com/sovannDeveloper/division.git
  video_player: ^2.9.5
  path_provider: ^2.1.5
  google_mlkit_object_detection: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/models/mobilefacenet.tflite