name: tflite_flutter
description: TensorFlow Lite Flutter plugin provides an easy, flexible, and fast Dart API to integrate TFLite models in flutter apps across mobile and desktop platforms.
version: 0.12.1
homepage: https://github.com/tensorflow/flutter-tflite

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  path: ^1.9.1
  quiver: ^3.2.2
  ffi: ^2.1.5

dev_dependencies:
  ffigen:
  flutter_lints:
  flutter_test:
    sdk: flutter
  melos:
  test:

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true